### ISSUE TITLE
Is the 'augeas' submodule needed?

### ISSUE THREAD

**Issue by sjorge** [hercules-team/augeasproviders_syslog#6]
Hi All,

I noticed that some of the augeasproviders_* modules checkout 'augeas' as submodule, is this required?
The augeas repository pulls in .gnulib which is rather large, especially if it gets pulled in a few times.

**Comment by domcleal** [comment]
No, that's used only for testing. The released modules don't include it.

**Comment by sjorge** [comment]
@domcleal thanks for the info.
